name: Simple SSH Test

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Echo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Successfully connected to $(hostname)"
            echo "Branch: ${{ github.ref_name }} has been pushed!"
            echo "The time on the server is: $(date)"
            echo "Server: $(hostname)"